### ISSUE TITLE
Writer for just outputting images (ic/od/is)

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/wai-annotations#27]
In order for a prediction job (image classification/ic, object detection/od or image segmentation/is) to obtain the images from the backend, a *fake* data format needs to be supplied. It would be useful to have a `to-images` writer that just outputs the images without any annotations. This writer would work for ic/od/is domains.

**Comment by csterling** [comment]
Instead of a fake output writer, this is implemented with an ISP, `strip-annotations`, in 6a6f3da090e507174afb4dbd18615c42da4dd82f.

This ISP removes all annotations from any instances in the conversion pipeline, and can be used in conjunction with a writer that outputs an individual annotation file per data file to just write the data files. For the image domains, this could be `to-adams-od/ic` for object detection/classification, and `to-indexed-png-is` for segmentation.

**Comment by fracpete** [comment]
Great idea!

**Comment by csterling** [comment]
Released in [v0.5.1](https://github.com/waikato-ufdl/wai-annotations/releases/tag/v0.5.1)
